---
swagger: "2.0"
info:
  description: This is an API...
  version: 0.0.1
  title: MessMa IndoorNavigation API
  contact:
    email: wi15b099@technikum-wien.at
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost
